### ISSUE TITLE
Random voltage

### ISSUE THREAD

**Issue by ovm-plugin** [JeffMcClintock/SynthEdit-Tracking#51]
Hi Jeff,
Now that I can use SE 1.5, Random voltage module still output the same series of values, each time you launch a project.

It's a bug that you have promised to resolve for SE 1.5.

Thanks,

OVM

**Comment by JeffMcClintock** [comment]
@ovm-plugin This is fixed with the "Random2" module. Replace your old module with this.
Note: It has a float output, so you might need to use a float-to-volt if you want to customise the amount of smoothing on the output.

 The old random module must remain unchanged so as not to break anyone existing projects.

**Comment by ovm-plugin** [comment]
Thanks Envoyé depuis mon mobile Huawei-------- Message original --------Objet : Re: [JeffMcClintock/SynthEdit-Tracking] Random voltage (Issue #51)De : Jeff McClintock À : JeffMcClintock/SynthEdit-Tracking Cc : ovm-plugin ,Mention 
@ovm-plugin This is fixed with the "Random2" module. Replace your old module with this.
Note: It has a float output, so you might need to use a float-to-volt if you want to customise the amount of smoothing on the output.
The old random module must remain unchanged so as not to break anyone existing projects.
