### ISSUE TITLE
VST3 on macOS shows all fonts in plugin windows one line too low

### ISSUE THREAD

**Issue by MrPlugDev** [JeffMcClintock/SynthEdit-Tracking#52]
Studio One 6, Cubase 13 and other DAWS on macOS show all fonts in the plug-in window one line too low (VST3). VST3 plug-ins are displayed ok only in Reaper. 

#tag: Bug

**Comment by JeffMcClintock** [comment]
@MrPlugDev Thanks, I ran a test plugin on both Windows and macOS. Most fonts that I tried (Times, Courier, Arial)  displayed consistently on both. The font 'Segoe UI' did not display exactly the same because the mac did not have this font installed.

![image](https://github.com/user-attachments/assets/98cae557-5152-43a5-b624-39d297fe0df9)


Can you elaborate some more please. Do you know which font show the problem, and which module has the problem?

**Comment by JeffMcClintock** [comment]
![image](https://github.com/user-attachments/assets/54dbabb4-5a05-44a2-aba0-4a3a10c99a1d)
I tried the plugin on both macOS and Windows, here is the difference I observed between the font alignments (it's a gif that switches between mac/Windows).

@MrPlugDev  Is this the difference that you are experiencing?

**Comment by JeffMcClintock** [comment]
![VintageGlowTextAlign](https://github.com/user-attachments/assets/de625b71-2bb6-4bb5-8a92-6cee7960532e)

**Comment by JeffMcClintock** [comment]
fix is available in SE 1.5 build #569
